# 数据库的连接新
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql-master.sango-mall.svc.cluster.local.:3306/mall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: nacos.sango-mall.svc.cluster.local.:8848
    sentinel:
      transport:
        client-ip: localhost
        port: 8719
        dashboard: sentinel.sango-mall.svc.cluster.local.:8858
  application:
    name: mall-memeber

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 主键自增
server:
  port: 20300
management:
  endpoints:
    web:
      exposure:
        include: '*'
