apiVersion: apps/v1
kind: Deployment
metadata:
  name: renren-fast
  namespace: sango-mall
  labels:
    app: renren-fast
spec:
  replicas: 1
  selector:
    matchLabels:
	  app: renren-fast
	template:
	  metadata:
	    labels:
		  app: renren-fast
	  spec: 
	    containers: 
		- name: renren-fast
		  image: $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:latest
		  imagePullPolicy: Always
		  ports:
		  - name: renren-fast
		    containerPort: 8093
		  resource: 
		    limits:
			  cpu: 1000m
			  memory: 500Mi
			requests:
			  cpu: 10m
			  memory: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: renren-fast
  namespace: sango-mall
  labels:
    app: renren-fast
spec:
  selector:
    app: renren-fast
  ports:
  - name: svc-renren-fast
    port: 8093
	targetPort: 8093
